import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../_components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="max-w-screen-xl mx-auto"
      >
        <Navbar />
        <main className="max-w-screen-xl min-h-550 h-screen max-h-800">
          <section className="border-2 border-black min-h-[600px] h-5/6 max-h-800">

            {children}

          </section>
        </main>
      </body>
    </html>
  );
}
